### ISSUE TITLE
migration to JME 3.1

### ISSUE THREAD

**Issue by meltzow** [brainless-studios/alchemist#19]
hi, 
if there are any plans to migrate to jmonkey 3.1 (currently in alpha 5) version, there are a first try here https://github.com/meltzow/alchemist/tree/jme3.1
If I remember correctly there is a crash in material "assets/matdefs/MyTerrainLighting.j3md" , I dont understand why.

**Comment by methusalah** [comment]
Both alchemist and cosmovania have been tested with jme 3.1 without any problem at many times. But at last news, jme 3.1 don't support jBullet integration anymore, wich is a needed feature. And it's still in alpha unstable version.

So unless we find a real advantage in that migration, I will continue to use jme 3.0. There is no major backward incompatibility anyway and it's only a matter of changing the version number in gradle, plus a tiny renaming in particle system

**Comment by meltzow** [comment]
the advantages will be the easy zay-es 1.2.1 integrtaion (https://github.com/jMonkeyEngine-Contributions/zay-es/releases). But it need jme 3.1 because there the networking is strong refactored. 
the missing jbullet integration in 3.1 is bad. 
is it possible to create a jme 3.1 branch for the future migration? like I described, I had some trouble with 3.1.

**Comment by methusalah** [comment]
just change de jmonkey version number in alchemist/build.gradle with this one : monkeyengine_version = '3.1.0-SNAPSHOT'

**Comment by meltzow** [comment]
ok, the sample is working with jme3.1. here its the branch. https://github.com/brainless-studios/alchemist/tree/jme3.1

but we got the following exception: 

**ERROR logic.processor.rendering.sprite.SpriteProc - Exception in processor : SpriteProc : Material parameter is not defined: UseAlpha
java.lang.IllegalArgumentException: Material parameter is not defined: UseAlpha
	at com.jme3.material.Material.checkSetParam(Material.java:459)
	at com.jme3.material.Material.setParam(Material.java:475)
	at com.jme3.material.Material.setBoolean(Material.java:624)
	at logic.processor.rendering.sprite.SpriteProc.getSprite(SpriteProc.java:65)
	at logic.processor.rendering.sprite.SpriteProc.onEntityUpdated(SpriteProc.java:46)
	at logic.processor.rendering.sprite.SpriteProc.onEntityAdded(SpriteProc.java:36)
	at com.brainless.alchemist.model.ECS.pipeline.BaseProcessor.update(BaseProcessor.java:63)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:287)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:243)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:745)**

**Comment by methusalah** [comment]
please delete that line

https://github.com/brainless-studios/alchemist/blob/master/sampleProject/src/main/java/logic/processor/rendering/sprite/SpriteProc.java#L65

That was already not needed in 3.0. it must have been cleaned in 3.1

**Comment by meltzow** [comment]
ok great. working now. Sample Project and supernovae is working.
